name: gelbooru
description: A universal package for connectiong ot various gelbooru based imageboards.
version: 3.1.4
repository: https://github.com/shalien/gelbooru

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  xml: ^6.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
