name: booru_dart
description: A simple wrapper for Booru based image boards API.
version: 0.0.4
repository: https://github.com/shalien/booru_dart

environment:
  sdk: ^3.0.5

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
